version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rbacdb
      - SPRING_DATASOURCE_USERNAME=rbacuser
      - SPRING_DATASOURCE_PASSWORD=rbacpassword
    networks:
      - rbac-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=rbacdb
      - POSTGRES_USER=rbacuser
      - POSTGRES_PASSWORD=rbacpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - rbac-network

networks:
  rbac-network:
    driver: bridge

volumes:
  db-data: