version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rbacdb
      - SPRING_DATASOURCE_USERNAME=rbacuser
      - SPRING_DATASOURCE_PASSWORD=rbacpassword
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rbacdb
      - POSTGRES_USER=rbacuser
      - POSTGRES_PASSWORD=rbacpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rbacuser -d rbacdb"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata: